export const ACCESS_TOKEN_SESSION_STORAGE_KEY_NAME = 'access_token';
export const NUM_REPOS_PER_PAGE = 10;

export const HTTP_FORBIDDEN_RESPONSE_STATUS_CODE = 403;
export const HTTP_UNAUTHORIZED_RESPONSE_STATUS_CODE = 401;
export const HTTP_NOT_FOUND_RESPONSE_STATUS_CODE = 404;
export const HTTP_OK_RESPONSE_STATUS_CODE = 200;

export const GITHUB_CONTEXT_REFRESH_ACTION_NAME = 'REFRESH';