name: Deploy to GitHub Pages

on:
  push:
    branches: [ 'main' ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build
      run: |
        npm install
        npm run-script build
      env:
        REACT_APP_AES_KEY: ${{ secrets.REACT_APP_AES_KEY }}
        REACT_APP_BFF_URL: ${{ secrets.REACT_APP_BFF_URL }}
        REACT_APP_CLIENT_ID: ${{ secrets.REACT_APP_CLIENT_ID }}
        REACT_APP_CONTACT_URL: ${{ secrets.REACT_APP_CONTACT_URL }}
        REACT_APP_DOCUMENTATION_URL: ${{ secrets.REACT_APP_DOCUMENTATION_URL }}
        REACT_APP_OAUTH_URL: ${{ secrets.REACT_APP_OAUTH_URL }}

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: build